### PR TITLE
fix for fly 1.3

### PR DESCRIPTION
**Pull request by lukeed**
In 1.3, `options.filename` was removed in favor of `options.file`. 

This ordering will force-set the `file: filename` value.

Should publish a minor version update with this

### CODE REVIEW

**Comment by t-jindai** [comment]
@lukeed Thank you for PR. 👍  Could you fix test too ?

**Comment by lukeed** [comment]
Just did :)

**Comment by lukeed** [comment]
I'm not sure what "path" Travis thinks is missing. Tests pass locally on all node versions, including 0.12

**Comment by lukeed** [comment]
D'oh! As of 1.0, `Flyfile.js` has to be lowercase now. Mac OSX isn't case-sensitive, so it wasn't throwing on my tests 😆 

@kashiro Ready for squash 👍

**Comment by t-jindai** [comment]
@lukeed thanks a lot 👍 

I think that we can not use `options.filename` at all so it is kind of `breakingchange` so I updated major version according to http://semver.org/

https://www.npmjs.com/package/fly-sass it's `v1.0.0`

**Comment by lukeed** [comment]
OK, that makes sense too 👌 

Thanks kashiro

**Pull request merged**
