### PR TITLE
Upgrade for Fly@2

### PR DESCRIPTION
**Pull request by lukeed**
Upgrades to the new plugin syntax.
### Changes
- Upgrade `node-sass` to 3.10+
- Use `file` option only (vs `data` combo), which uses internal intelligent parser
  - simplifies / removes need for `includePaths`
  - SASS and/or SCSS with no extra setup
- Add `sourceMaps` support
- Upgrade test suite
- Provide examples within `readme.md`
### Other

@tomoyukikashiro:
1. Please change the repo description to: "Node Sass plugin for Fly."
2. Please publish as `2.0.0`

Thanks!

### CODE REVIEW

**Comment by lukeed** [comment]
If you restart the Travis job, it will pass. I pushed before the related Fly changes were published.

**Comment by lukeed** [comment]
hey @tomoyukikashiro, if you have 5min I'd really appreciate it if you merged this --- it's one of my core plugins.

Thanks!

**Review by kcolton — CHANGES_REQUESTED** [review]
@lukeed Do we really need to get into the tabs versus spaces religious debate? Generally you keep to the maintainers formatting.

https://github.com/felixge/node-style-guide#2-spaces-for-indentation

**Comment by lukeed** [comment]
@kcolton I generally don't care; it was my automator. I'm combing thru the majority of fly plugins. So it's for consistency. Plus, this plugin was made with `generator-fly`, which I made & originally _did_ use spaces. It wasn't kashiro's deliberate choice. 😉 

My turn: ["Why tabs are superior"](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/)

**Comment by t-jindai** [comment]
@kcolton Thanks for you comments.
@lukeed Thanks PR 👍 

I know you are one of `flyjs` contributor and `flyjs`use `tab`.
As you mentioned that this plugin was made with `generator-fly` so I want to follow that generator style now.

So.. plz change them 🙇 
- change tab to space [https://github.com/tomoyukikashiro/fly-sass/pull/13/commits/35e1eedf0f40197c39b7410f851d4c4a942929c8]
- make top level files uppercase [https://github.com/tomoyukikashiro/fly-sass/pull/13/commits/4a7e4ed105a00e2f11998a9e1b93fd5f7793dc9c]

thanks,

**Comment by lukeed** [comment]
@tomoyukikashiro Not a problem 👍

**Comment by t-jindai** [comment]
@lukeed thanks 👍

**Comment by t-jindai** [comment]
@lukeed I've just published it to npm 🚀  https://www.npmjs.com/package/fly-sass

**Comment by lukeed** [comment]
@tomoyukikashiro Thank you! 🍾

**Comment by lukeed** [comment]
@tomoyukikashiro Oh, you should also update the repo's description. 

It says: "Fly plugin for Less".

I would change it to: "Node Sass plugin for Fly." so that it's the same as NPM.

**Pull request merged**
