### PR TITLE
update to fly@0.7.0 new API

### PR DESCRIPTION
**Pull request by ghost**
Also notice this strange part:

``` js
assign({ outFile: options.sourceMap ? "." : "" }, options))
```

@akhleung @xzyfer
I don't know why, but libsass requires you to set `outFile` in order to produce a sourcemap. Fly handles sourcemap internally so if we don't do this users will need to specify that `outFile` when they don't need it (they can still specify when they do and Fly will favor it in that case).

### CODE REVIEW

**Comment by xzyfer** [comment]
This is because the sourcemaps needs to know the which output file the input file is being mapped to.

**Comment by xzyfer** [comment]
It's also worth noting node-sass isn't compatible iojs 3 yet, hence the build failure you're seeing.

This will be fixed in the upcoming 3.3 release.

**Comment by ghost** [comment]
@xzyfer Thanks Michael.

**Comment by t-jindai** [comment]
Thanks :) @bucaran

**Comment by ghost** [comment]
:+1: :+1:

**Pull request merged**
